metric: VOC
map_type: 11point
num_classes: 3

TrainDataset:
  name: VOCDataSet
  dataset_dir: /home/aistudio/work/dataset
  anno_path: train_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: /home/aistudio/work/dataset
  anno_path: val_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: /home/aistudio/work/dataset/labels.txt
